### ISSUE TITLE
Add animation to readme!

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari-animation#107]
@alisterburt I'd like to update the readme so it looks better on https://www.napari-hub.org/plugins/napari-animation and includes a playable movie - see like what i did with https://www.napari-hub.org/plugins/waver and https://github.com/sofroniewn/waver/blob/main/README.md where I uploaded to movie to a dedicate github issue and then used to url from there to link too https://github.com/sofroniewn/waver/issues/9

**Comment by alisterburt** [comment]
@katherine-hutchings this could be a good one for you to take on to get used to collaborating on code with git/github

A general outline of what would be needed is
1) fork the repo and download it so you are working on a local copy ([some notes](https://gist.github.com/Chaser324/ce0505fbed06b947d962))
2) setup your dev environment (new conda env, install necessary packages etc)
3) play with the animation plugin a bit in napari, try to understand how it works
4) make a nice animation using the plugin (maybe with [this example data](https://github.com/alisterburt/napari-cryo-et-demo)?)
5) upload the movie (.mp4) into this github issue
6) update the README of this project with a link to the movie (following the pull request workflow outlined in the notes above)

This is quite a lot of new stuff to take in so going through the process on something non-technical will hopefully be one less thing to think about - feel free to ping me here or on the [napari zulip](https://napari.zulipchat.com/) with any questions
