### ISSUE TITLE
animation with canvas becomes grayscale due to screenshot flash (Apple M1)

### ISSUE THREAD

**Issue by maweigert** [napari/napari-animation#110]
Hi, 

First off, thanks a lot for this amazing and really valuable plugin! 

### Description

I noticed that for some image sequences (especially large images) the animation grayes out when using the "with Canvas" capture mode on the current main branch.  

Example (for "Hubble Deep Field" scikit image test data):

https://user-images.githubusercontent.com/11042162/142061544-7367c195-555f-4044-921d-a8a61d9adc94.mp4

### Possible Fix

Using `flash=False` in the [respective render code](https://github.com/napari/napari-animation/blob/b192a98b95d16ccff10f6edcb95c445a9c11eb27/napari_animation/key_frame.py#L86):

```python 
return viewer.screenshot(canvas_only=canvas_only, flash=False)
```  
fixes this.

### Env info

```
napari: 0.4.12
Platform: macOS-11.6-arm64-arm-64bit
System: MacOS 11.6
Python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:22:19) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.4
SciPy: 1.7.2
Dask: 2021.11.1
VisPy: 0.9.3

OpenGL:
- GL version: 2.1 Metal - 71.7.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0

Plugins:
- animation: 0.0.3.dev78+gb192a98.d20211116
- console: 0.0.4
- scikit-image: 0.4.12
- svg: 0.1.5
```

**Comment by alisterburt** [comment]
Thanks for using the plugin @maweigert ! That's what I get for neglecting a repo while napari marches on 😆 will fix and push a release
