### ISSUE TITLE
jumpy transitions between keyframes

### ISSUE THREAD

**Issue by alisterburt** [napari/napari-animation#113]
looks like there has been some sort of regression which makes the transitions between keyframes jump around

I'm not sure under what circumstances it occurs exactly yet, it seems like playing with the preview slider before capturing keyframes is part of the problem

https://user-images.githubusercontent.com/7307488/142078462-9089fa3e-c61d-43ad-bb99-59bcd389c6b4.mp4

@maweigert you were using the plugin recently, is this something you ran into?

**Comment by maweigert** [comment]
> @maweigert you were using the plugin recently, is this something you ran into?

Hm, I didn't run into it, yet I can reproduce it...

**Comment by alisterburt** [comment]
thanks for taking a look! I'll keep digging 🙂

**Comment by alisterburt** [comment]
unsuccesful bug hunt, need to call it quits for tonight, mini report...

- appears with version `0.0.2` of napari-animation from pip
- appears with recent napari versions `0.4.10` and `0.4.11`
- appears with recent vispy versions `0.8.1`
- appears to be a zoom problem but zoom values in `Animation._frames.camera['zoom']` appear correct for a jumpy animation

```ipython
for i in range(31):
    print(animation._frames[i].camera['zoom'])
    
1.890401643454949
1.8904016434549489
1.8904016434549489
1.8904016434549489
1.8904016434549487
1.8904016434549487
1.8904016434549487
1.8904016434549487
1.8904016434549487
1.8904016434549487
1.8904016434549487
1.8904016434549487
1.8904016434549484
1.8904016434549484
1.8904016434549484
1.8904016434549484
1.8904016434549484
1.8904016434549484
1.8904016434549484
1.8904016434549487
1.8904016434549487
1.8904016434549487
1.8904016434549487
1.8904016434549487
1.8904016434549487
1.8904016434549487
1.8904016434549487
1.8904016434549489
1.8904016434549489
1.8904016434549489
1.890401643454949
```

I recently installed this and other things into a fresh environment on another machine and didn't have any problems. 
Bug is definitely not super reproducible so far...

**Comment by alisterburt** [comment]
fixed upstream in vispy!
