### ISSUE TITLE
Hook up plane model from volume visualization

### ISSUE THREAD

**Issue by brisvag** [napari/napari-animation#116]
`SlicingPlane` from the `Image` layer is not yet hooked up to the animation interpolation.

**Comment by alisterburt** [comment]
Yep - unfortunately only base state is captured right now, there were some unexpected visual changes when everything from `layer._get_state()` was used but this was a while ago

if you like you could try changing below to `layer._get_state()`?

https://github.com/napari/napari-animation/blob/7f49d2c360ec0231e5a2d15394125856d439cdde/napari_animation/viewer_state.py#L26-L36
