### ISSUE TITLE
plugin not working with napari==0.4.17rc2

### ISSUE THREAD

**Issue by alisterburt** [napari/napari-animation#130]
the first release candidates for the next napari release 0.4.17 [are available](https://napari.zulipchat.com/#narrow/stream/215289-release/topic/v0.2E4.2E17rc2) and it seems napari-animation is incompatible - we should fix this and push a release prior to release of napari

@katherine-hutchings would you be interested in working together on this?

**Comment by katherine-hutchings** [comment]
I've just tested against 0.4.17rc4 and things appear to be working. :)

**Comment by alisterburt** [comment]
thanks katherine, closing!
