### ISSUE TITLE
napari-animation excessive memory usage

### ISSUE THREAD

**Issue by JoOkuma** [napari/napari-animation#143]
Hi, I had some problems running napari-animation with large datasets. It uses too much memory, sometimes even crashing due to running out-of-memory.

I think the problem is in [here](https://github.com/napari/napari-animation/blob/d8bd60939fb844e564ca54a5481cd0e2a80f854c/napari_animation/frame_sequence.py#L90-L111), where the `_cache` that keeps growing without limit.

**Comment by JoOkuma** [comment]
Defining a maximum cache size fixes the issue, should I open a PR?

**Comment by alisterburt** [comment]
ooft! Yes please, PR would be welcome, thanks @JoOkuma !

**Comment by psobolewskiPhD** [comment]
I *think* this can be closed by: https://github.com/napari/napari-animation/pull/150
?

**Comment by JoOkuma** [comment]
Yes, thanks @psobolewskiPhD. Closed by #150
