### ISSUE TITLE
Example Animation: Plane normal

### ISSUE THREAD

**Issue by AlexSauer** [napari/napari-animation#157]
Not really an issue but more a question:

In the example animation, your 'layer controls' part of the napari window shows items 'plane normal' and 'plane 'thickness'
<img width="219" alt="Screenshot 2023-03-07 at 10 09 36" src="https://user-images.githubusercontent.com/22394318/223391111-b8e4bccb-00fd-4679-97c4-998ce90404a3.png">

Can you explain how I can enable these features? The standard version as shown [here](https://napari.org/stable/) doesn't seem to include them?
Thanks a lot!

**Comment by alisterburt** [comment]
Hi @AlexSauer, thanks for reaching out! In 3D view volumetric data can be depicted in napari as either a volume (default) or a plane, this is controlled by setting `Image.depiction` to `"volume"` or `"plane"` or using the depiction dropdown in the layer controls

Does this clear things up for you? :)

**Comment by AlexSauer** [comment]
Absolutely amazing, thanks a lot!! :)
