### ISSUE TITLE
Event refactors

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari-animation#18]
Follow up from #14, stop recreating `EventedList` and make the `frame` property evented (note here we might want to wait until after https://github.com/napari/napari/pull/2127 is available as it might make this much cleaner) - cc @alisterburt

**Comment by alisterburt** [comment]
Had a quick go at eventing the frame counter this evening and didn't get too far. How would you go about doing this? Is making the frame attribute into the value of a QSpinBox the completely wrong way to go?

**Comment by sofroniewn** [comment]
This will be much easier after the next napari release that contains https://github.com/napari/napari/pull/2127, but I would then turn [Animation](https://github.com/sofroniewn/napari-animation/blob/b64f943fdc0b76a61a2cb2a569ed5c1ce27dff81/napari_animation/animation.py#L12) into an `EventedModel` (I'd probably make `viewer` a private attribute too), and then you'll get an `animation.events.frame` eventemitter for free and you can connect that into whatever you like. Certainly it should connect into the "selected" aspect of the QLayerList, so that when you change the frame you update which keyframe is selected and visa-versa. I'm not quite sure I see why you want the QSpinBox too, but maybe I'm missing something

**Comment by alisterburt** [comment]
Okay that sounds great, the EventedModel (and pydantic in general) look super useful. Thanks!

The QSpinBox was just the only way I could think of to get a number which emitted events on changing value that I could connect to - probably showing my naivety 😝 the EventedModel will solve the problem perfectly
