### ISSUE TITLE
[Maintenance] re-consider [dev] PyQt5 dependency 

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari-animation#185]
Currently:
https://github.com/napari/napari-animation/blob/a9ca7a7a96e5b281bf80815aaded8a6ce0b72872/setup.cfg#L53

This is a bit annoying when on arm64 where pyqt6 has wheels on pypi, but pyqt5 does not -- soon to change, but still. There's a dependency on qtpy and napari, should suffice to document needing a Qt backend, but not force a specific one?

**Comment by brisvag** [comment]
Agree :+1:
