### ISSUE TITLE
animation fails to run with a spot layer

### ISSUE THREAD

**Issue by sebherbert** [napari/napari-animation#207]
Hi all, hi @guiwitz,

We've tried to create an animation containing some spots that were detected but ended up with this error. 
Would you have some idea what the problem could be and if we could fix it on our side maybe?
![napari_animation_spot_fail](https://github.com/napari/napari-animation/assets/29088372/663581aa-53bc-4c11-b35f-28bbd59eae31)

Packages installed:

> python 3.11.7
> napari                    0.4.18                   pypi_0    pypi
> napari-animation          0.0.7                    pypi_0    pypi
> napari-console            0.0.9                    pypi_0    pypi
> napari-crop               0.1.9                    pypi_0    pypi
> napari-nd-cropper         0.1.3                    pypi_0    pypi
> napari-plugin-engine      0.2.0                    pypi_0    pypi
> napari-plugin-manager     0.1.0a2                  pypi_0    pypi
> napari-roi                0.1.8                    pypi_0    pypi
> napari-svg                0.1.10                   pypi_0    pypi
> napari-tools-menu         0.1.19                   pypi_0    pypi
> napari-workflows          0.2.10                   pypi_0    pypi

Thanks!
Sebastien

**Comment by psobolewskiPhD** [comment]
I *think* this should have been fixed by: https://github.com/napari/napari-animation/pull/181

We just haven't made a release.

If you're comfortable testing, can you try to installing the main branch from here via:
`python -m pip install "git+https://github.com/napari/napari-animation.git` 

If that doesn't work then we'll need a bit more info about the layers or ideally some code to reproduce.

**Comment by sebherbert** [comment]
Thanks for the quick reply and suggestion. We'll give it a try as soon as possible!

**Comment by psobolewskiPhD** [comment]
Thanks, I will sort out whats blocking release in the 2nd half of this week -- we had some administrative/permissions blockers, that hopefully are resolved.

**Comment by psobolewskiPhD** [comment]
Sorry for the delay!
0.0.8 should be out now:
https://pypi.org/project/napari-animation/

Hopefully it fixes your issue. If not, re-open!

**Comment by sebherbert** [comment]
Sorry we didn't have the time to retest either...
Thanks, I'm looking forward to give it a try!
