### ISSUE TITLE
Add a Record mode

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari-animation#21]
Could we add support for a record mode where we captured all events, mouse etc, and then store them for playback to make automated movies like is discussed https://github.com/napari/napari/issues/1387#issuecomment-769984161.

We probably want the recording functionality to be handled by some macro-recorder that could live as its own napari plugin or in the main repo.

We could then put this functionality inside it's own dedicated repo, but I think it might be nice to be able to mix and match the "recording" style and the "key-frame" style

**Comment by alisterburt** [comment]
closing as out-of-scope for now - if someone feels strongly about this feel free to reopen!
