### ISSUE TITLE
Switch deploy method to use trusted publisher

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari-animation#211]
Right now we have a trusted publisher configured on PyPI but our deploy workflow still uses `twine` and its secret token to upload new releases.

We should update the workflow file to remove the use of `twine` in favour of the `pypa/gh-action-pypi-publish@release` action as described [here](https://docs.pypi.org/trusted-publishers/using-a-publisher/).

**Comment by GenevieveBuckley** [comment]
Three things need to happen:
1. [Add a trusted publisher to our existing PyPI project](https://docs.pypi.org/trusted-publishers/adding-a-publisher/) (or you can [create a new PyPI project with a trusted publisher](https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/)).
2. Merge a PR updating .github/workflows/release_drafter.yml. The deploy job needs to be given id-token: write permissions, and changed to use the [pypa/gh-action-pypi-publish](https://github.com/marketplace/actions/pypi-publish) action (see example [here](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/)).
3. Delete the old PyPI API tokens, from both PyPI and the GitHub repository secrets settings.

I can make a PR for (2), but do not have access to do (1) and (3). Someone else will have to do those.
