### ISSUE TITLE
Upgrade ruff target python version, and fix ruff check errors

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari-animation#215]
Ruff is targeting a very old version of python (python 3.8)
https://github.com/napari/napari-animation/blob/f3463af3aa39e60087e8714244c9773b95392e8e/pyproject.toml#L56

Upgrading the target version makes the ruff check fail. We should make a PR to:
* upgrade the ruff target version of python, and
* fix the ruff check errors

**Comment by psobolewskiPhD** [comment]
Ruff checks on CI seem to be passing:
https://github.com/napari/napari-animation/actions/runs/10733347312/job/29766561598?pr=234
and the target is "py39" which for the time being is still correct, so I think we can close thins.
We may consider using the ruff formatter at some point as we have done in the napari/napari repo just for simplicity.
