### ISSUE TITLE
interpolating plane position doesn't work in napari 0.5.X

### ISSUE THREAD

**Issue by TristanBeste** [napari/napari-animation#228]
I am pretty new to napari and i found the layer planes tutorial here. It would be the perfect fit to show my microscopy data but it is not working as intended for me. When i just run the tutorial i only get 4 frames instead of an smooth rendering like in the gif showen. I managed to get a similar result by looping through every z and afterward clipping multiple mp4 files together. Are there any dependencies I am missing to make it work 
this is how my results look from the jupyter notebook that is online
https://github.com/user-attachments/assets/f0b3a065-660d-4e9d-a572-9f51638c358e
thanks in advance

**Comment by alisterburt** [comment]
Hey @TristanBeste ! I agree that looks super weird - I can confirm that I see the same behavior. This must be something to do with the recent napari 0.5.X series of updates. @jni @psobolewskiPhD any immediate ideas what might be causing this?

**Comment by alisterburt** [comment]
to be clear, something is quite deeply wrong - I'm seeing what looks like bool interpolation between keyframes for the plane position rather than the specified (default) `Easing.LINEAR`

**Comment by TristanBeste** [comment]
i found a solution for now. I created an environment with napari = 0.4.11 and now its working 

https://github.com/user-attachments/assets/58b702fa-dd8e-4aa1-8a1f-32f8a3fa8643

thanks for your quick answer

**Comment by alisterburt** [comment]
@TristanBeste glad you found a solution and thank you for raising the issue here

**Comment by psobolewskiPhD** [comment]
Hi thanks for opening the issue. I can confirm that with the current napari-animation 0.0.8 interpolation rendering planes is broken in napari 0.5.x (I tested 0.5.0 and 0.5.3).
If I downgrade to napari 0.4.19post1 then everything works--I'd certainly recommend that version over going all the way back to 0.4.11--so this must be caused by a napari bug/regression.

**Comment by psobolewskiPhD** [comment]
Git bisect points to f9b917f2e22e0cdcb039417e0f8275c4b7e369c3
https://github.com/napari/napari/pull/6976
`as_layer_data_tuple` doesn't return a dict anymore, but a `_ DeprecatingDict` so probably some check is failing. As far as I can tell the individual attributes aren't changed, just the container, so not clear why this is happening, but it affects other components like gamma as well.

**Comment by psobolewskiPhD** [comment]
Ok, I think I see the problem. Here:
https://github.com/napari/napari-animation/blob/ba8ab537abd181ee5a8af0e821d3b889c46529b0/napari_animation/utils.py#L36-L48

We check if something is a dict when recursing. But `_DeprecatingDict` isn't a dict in this check, so it fails and doesn't recurse and then we can't interpolate properly.

**Comment by psobolewskiPhD** [comment]
So coercing the `as_layer_data_tuple` here to `dict` solves the problem.
https://github.com/napari/napari-animation/blob/ba8ab537abd181ee5a8af0e821d3b889c46529b0/napari_animation/viewer_state.py#L30-L41

**Comment by andy-sweet** [comment]
> So coercing the `as_layer_data_tuple` here to `dict` solves the problem.

With very little knowledge of `napari-animation`, that seems like the best fix for now because it should be relatively fast, and it also ensures that the thing actually is a `dict` (which is what it assumed before).

Sorry for the inconvenience caused here!
