### ISSUE TITLE
disable FrameWidget for first frame

### ISSUE THREAD

**Issue by alisterburt** [napari/napari-animation#24]
parameters in the `FrameWidget` don't have an effect on the animation - they shouldn't be editable from the GUI to indicate this

longer term a graph structure might make this more intuitive - key-frames are nodes and interpolation settings/order of animation come from the edges

**Comment by sofroniewn** [comment]
Yeah exactly, it's a bit funny - for `n+1` nodes we have `n` transitions. Not sure how to deal with this best

**Comment by alisterburt** [comment]
solution described in #77
