### ISSUE TITLE
save dialog issues

### ISSUE THREAD

**Issue by alisterburt** [napari/napari-animation#39]
I'm trying to incorporate extra layer metadata [over here](https://github.com/alisterburt/napari-animation/tree/layer-visibility) and keep running into what seems to be a low level Qt/system bug when trying to work with the save dialog. 

This has worked previously but the issue persisted after restart so leaving an issue here

```
2021-03-05 20:03:46.759 python[8310:261652] WARNING: <NSSavePanel: 0x7fecc3bfa3e0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
```

this [apple 'appkit' dev page](https://developer.apple.com/documentation/appkit/nssavepanel) has some info

**Comment by sofroniewn** [comment]
Hmm, i havn't seen this one before. Is it still a problem for you?

**Comment by alisterburt** [comment]
Has disappeared, thankfully, probably fixed in some OS update!
