### ISSUE TITLE
Setting properties one by one for images triggers many expensive redraws

### ISSUE THREAD

**Issue by alisterburt** [napari/napari-animation#54]
I ran into some 'too slow' issues when interactively animating a 3D scene (mentioned in #28) with a 500x500x400 volume

In particular, setting the animation state to a given key-frame is extremely slow. I'm pretty sure this is caused by the following
https://github.com/napari/napari-animation/blob/f5f797909e798c8da5c27cd72fdf7f3695bcb62c/napari_animation/animation.py#L142-L146

Which explicitly sets a bunch of properties on the layers, triggering redraws which can sometimes be expensive (e.g. larger 3D volumes)

I see two ways to solve this:
- checking for equality before setting properties to minimise redraws (easy, naive)
- attempting to only store diffs between key-frames as suggested by @sofroniewn in #40 

Will attempt the first option and if that doesn't make things feel smooth later will investigate more thoroughly

**Comment by alisterburt** [comment]
naive solution works!

**Comment by sofroniewn** [comment]
Ok nice, yeah - good catch - one we refactor the layers to be evented pydantic models we'll get the equality check for free, but till then we have to add it ourselves

**Comment by sofroniewn** [comment]
Closed by #55
