### ISSUE TITLE
CI failing on windows with openGL eorrs on vispy import

### ISSUE THREAD

**Issue by alisterburt** [napari/napari-animation#64]
https://github.com/napari/napari-animation/pull/61/checks?check_run_id=2465586503#step:9:132

This is the only thing stopping us from merging #61 which we want to merge before #49 which we want for the 0.0.1 release. 

Given that the error seems unrelated to our tests I'm tempted to just merge but merging in spite of failed CI feels like a wrong move 

@sofroniewn @tlambert03 any advice would be appreciated

**Comment by tlambert03** [comment]
the windows opengl installation has been fixed upstream in the meantime... so I just restarted the job. let's see if it passes

**Comment by tlambert03** [comment]
yep! https://github.com/napari/napari-animation/pull/61/checks?check_run_id=2469622790

**Comment by alisterburt** [comment]
the 🧙🏼‍♂️ strikes again! thanks!
