### ISSUE TITLE
Strange visual effects when scrolling AnimationSliderWidget

### ISSUE THREAD

**Issue by alisterburt** [napari/napari-animation#66]
There are strange visual effects when changing the `AnimationSliderWidget`

The cause is that the selected frame changes in the `KeyFramesListWidget` when the slider moves, triggering the selection callback which sets the animation to the current key-frame rather than the correct interpolated frame

This should be easy to fix by blocking that particular event which triggers that callback when the selection is changed by moving the slider

**Comment by sofroniewn** [comment]
Close by #69
