### ISSUE TITLE
Online docs/ Jupyterbook

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari-animation#70]
As mentioned in a couple PRs we should get online docs built for this package using jupyterbook.

We have to see how the best way to do this is, but it would be nice one day if either napari or [napari-hub](https://github.com/chanzuckerberg/napari-hub/) (our in-progress) plugin discovery site could then host the documentation cc @neuromusic @kne42 

We might also then want to update our cookiecutter with jupyter book too, cc @tlambert03, to make the whole workflow seemless and integrated!

**Comment by alisterburt** [comment]
Happy to put together a basic jupyterbook setup (stealing the napari.org colour scheme) this week

I'll get it set up to deploy to napari.github.io/napari-animation (default gh-pages site for a repo) then we can make sure everything is working before moving to napari/-hub?

**Comment by sofroniewn** [comment]
Great! Sounds like plan!!

**Comment by melissawm** [comment]
Hello 👋🏻 I believe this is not done yet, would you like some help? I'd be happy to give it a try.

**Comment by alisterburt** [comment]
Hey @melissawm - this would be incredible if you're interested! I have a fairly major preference for using mkdocs-material, the developer experience is just so nice, would that work for you?

**Comment by melissawm** [comment]
That sounds like a great learning experience 😄 I'm in!

**Comment by alisterburt** [comment]
@melissawm awesome! Let me know if you get stuck, very happy to help

**Comment by melissawm** [comment]
I was chatting with @kolibril13 today and he shared this: https://napari-animation-docs.readthedocs.io/

Looks super promising and we could collaborate on this!

**Comment by alisterburt** [comment]
Super keen for collaboration and work on the docs - less keen about maintaining a sphinx project moving forward :-)

**Comment by melissawm** [comment]
Yup - what we discussed is potentially having that as a starting point but on mkdocs. Maybe having a prototype makes it easier to visualize

**Comment by GenevieveBuckley** [comment]
I'm going to close this issue, as being mostly addressed by https://github.com/napari/napari-animation/pull/200

We still do not have executed jupyter notebook files as part of the docs, so I have opened a dedicated issue for that here: https://github.com/napari/napari-animation/issues/204
