### ISSUE TITLE
tests badge is broken

### ISSUE THREAD

**Issue by Fifourche** [napari/napari-animation#95]
At least on my side, the tests badge of the README file is broken ; the error code I get from Chrome developer tools is : 

`
Refused to load the image 'https://github.com/napari/napari/actions/workflows/test_comprehensive.yml/badge.svg' because it violates the following Content Security Policy directive: "img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com secured-user-images.githubusercontent.com/ *.githubusercontent.com".
`

**Comment by alisterburt** [comment]
strange, it's working for me with #94 (Chrome, MacOS) - not sure what we can do about that

**Comment by Fifourche** [comment]
On Windows it's ok with Firefox, but not Opera nor Chrome ; I'll probably close this issue as it's not related to this project in fact !
